application: slinger-dev
version: 01060000t
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /assignUser
  script: assignUser.py
  secure: always

- url: /syncUsers
  script: syncUsers.py
  secure: always

- url: /syncData
  script: syncData.py
  secure: always

- url: /syncSignatures
  script: syncSignatures.py
  secure: always
  
- url: /syncKeyNodes
  script: syncKeyNodes.py
  secure: always
  
- url: /syncMatch
  script: syncMatch.py
  secure: always
  
- url: /cron/cleanup
  script: cleanup.py

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico
  
- url: /.*
  script: main.py
  secure: always
